<?php
	
	$lang	= array
	(
		'terms_page_title'	=> 'Terms of Use - #SITE_TITLE#',
		
		'terms_title'	=> 'Terms of Use',
		'terms_content'	=> '
			<p><strong>Privacy Policy</strong></p>
			<p>Blogtronix LLC is absolutely committed to your privacy in any aspect and guards your personal and business information to the best of our capabilities. We know and see that the great and exciting growth of the Internet and all the types of online services has also brought reasonable concern for consumers about what information is collected, distributed and available about them, and we want you to be sure that we always consider and work with that diligent and honest commitment to all of our Internet activities.</p>
			</p>We have taken, take and will take all the appropriate steps to protect your privacy while you are with us online. Whenever you provide personal or business sensitive information - demographic information, personal details, a credit card number to make a purchase, we always take reasonable steps to protect it, such as encrypting this information. We also take reasonable security measures to protect your personal and business information in storage.</p>
			<p>We do not and will not provide any of your personal or business information to other companies or individuals without your specific request and permission. It is possible though that we may need to provide your name and delivery address to third parties that Blogtronix LLC uses for delivering specific services to you - like shipping companies if you have asked us to send something to you.</p>
			<p><strong>Terms of Use</strong></p>
			</p>By accessing Blogtronix LLC World Wide Web pages and the Blogtronix Business Blogging and Social Networking Online System you agree to the following terms. If you do not agree to the following terms, please notice that you are not allowed to use this website.</p>
			<p>The contents of Blogtronix LLC World Wide Web pages and Blogtronix Blogging System are Copyright © Blogtronix LLC 2005. Any rights not expressly granted herein are reserved. Reproduction, transfer, distribution or storage of part or all of the contents in any form without the prior written permission of Blogtronix LLC is prohibited except in accordance with the following terms. Blogtronix LLC consents to you browsing Blogtronix LLC World Wide Web pages and Blogtronix Blogging System on your computer or printing copies of extracts from these pages for your personal use only and not for redistribution unless consented to in writing by Blogtronix LLC. Individual documents in our World Wide Web pages and Blogtronix Blogging System may be subject to additional terms indicated in those documents.</p>
			<p>The use of this site and the content therein, is permitted to private, non-commercial use unless stated otherwise in writing. The use of news and press releases and other documents classified as public is permitted in public communications if the source for the information has been stated.</p>
			<p>This site, the blogging system and the contents herein are provided as a convenience to you. The contents of Blogtronix LLC World Wide Web pages and the Blogtronix Blogging System are provided on "as is" and "as available" basis. Blogtronix LLC does not warrant that its Web pages will be uninterrupted or error-free. Blogtronix LLC reserves the right to revise the pages or withdraw access to them at any time.</p>
			<p>NO WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF TITLE OR NON-INFRINGEMENT OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, IS MADE IN RELATION TO THE AVAILABILITY, ACCURACY, RELIABILITY OR CONTENT OF THESE PAGES. BLOGTRONIX LLC SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR FOR BUSINESS INTERRUPTION ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SERVICE, EVEN IF BLOGTRONIX LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW EXCLUSION OF CERTAIN WARRANTIES OR LIMITATIONS OF LIABILITY, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THE LIABILITY OF BLOGTRONIX LLC WOULD IN SUCH CASE BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
			<p>For your easy accessibility Blogtronix LLC may include links to sites on the Internet that are owned or operated by third parties. By linking to such third-party site, you shall review and agree to that site\'s rules of use before using such site. You also agree that Blogtronix LLC has no control over the content of that site and cannot assume any responsibility for material created or published by such third-party sites. In addition, a link to a non-Blogtronix LLC site does not imply that Blogtronix LLC endorses the site or the products or services referenced in such third party site.</p>
			<p>By submitting material to any of our servers, for example, by e-mail or via the Blogtronix LLC World Wide Web pages or using Blogtronix Blogging System, you agree that: (a) the material will not contain any item that is unlawful or otherwise unfit for publication; (b) you will use reasonable efforts to scan and remove any viruses or other contaminating or destructive features before submitting any material; and (c) you own the material or have the unlimited right to provide it to us and Blogtronix LLC may publish the material free of charge and/or incorporate it or any concepts described in it in our products without accountability or liability (d) you agree not to take action against us in relation to material that you submit and you agree to indemnify us if any third party takes action against us in relation to the material you submit.
			Blogtronix LLC does not and cannot review the content posted by users on its site or on Blogtronix Blogging System and is not responsible for such content. Blogtronix LLC may at any time at its discretion remove any content posted by users.</p>
			<p>Blogtronix and Blogtronix Blogging System are registered trademarks of Blogtronix LLC. Blogtronix LLC\'s product names are either trademarks or registered trademarks of Blogtronix LLC. Other product and company names mentioned herein may be trademarks or trade names of their respective owners. Your access to this site should not be construed as granting, by implication, estoppel or otherwise, any license or right to use any marks appearing on the site without the prior written consent of Blogtronix LLC or the third party owner thereof.</p>',
	);
	
?>